%YAML:1.0
---
cameraDataPath: "config/out_camera_data_zhx.yml"
silPath: "data/pineapple/mask*.jpg"
imagesPath: "data/pineapple/pineapple_*.jpg"
filenameOut: "result.off"
resolution: 100
mc_length_x: 300
mc_length_y: 300
mc_length_z: 700
markersX: 5
markersY: 7
markerLength: 33
markerSeparation: 7
dictionaryId: 15
