%YAML:1.0
---
cameraDataPath: "config/out_camera_data.yml"
silPath: "data/background_subtraction/c_day_green_apple*.jpg"
imagesPath: "data/background_subtraction/day_green_apple*.jpg"
filenameOut: "result/result_apple.off"
resolution: 100
mc_length_x: 300
mc_length_y: 300
mc_length_z: 300
markersX: 5
markersY: 7
markerLength: 33
markerSeparation: 7
dictionaryId: 15
